Repository infostart-hub/snegopat, pull requests merged in 2020-10, with the labels that each got.

#61 Настройки переноса строк + гит игнор
  .gitattributes
  .gitignore
Labels: hacktoberfest-accepted

#65 Уточнил развертывание репозитория
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest-accepted

#66 Шаблоны гитхаба
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/help_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: hacktoberfest-accepted

#67 Руководство по работе с TypeScript в markdown
  CONTRIBUTING.md
  docs/10 develop-start.md
  docs/99 snegapi.md
Labels: documentation, hacktoberfest-accepted

#71 Поиск и замена
  addins/extSearch.epf
  addins/extSearch.js
  addins/extSearch.results.ssf
  addins/extSearch.ssf
  tools/dynwrapx.dll
Labels: enhancement, hacktoberfest-accepted

#79 Информация, как синхронизироваться с основным репо
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted
