Repository infostart-hub/snegopat, pull requests merged in 2021-02, with the labels that each got.

#128 Анализ дампов Снегопата - упрощение запуска для новых платформ 1С + запуск на 8.3.18.1289
  .gitignore
  docs/20 tools-1c.md
  docs/readme.md
  tools/1с/src/СравнениеДамповСнегопата/СравнениеДамповСнегопата.xml
  tools/1с/src/СравнениеДамповСнегопата/СравнениеДамповСнегопата/Forms/Форма.xml
  tools/1с/src/СравнениеДамповСнегопата/СравнениеДамповСнегопата/Forms/Форма/Ext/Form.xml
  tools/1с/src/СравнениеДамповСнегопата/СравнениеДамповСнегопата/Forms/Форма/Ext/Form/Module.bsl
  v8api/bkendui.v
  v8api/metadata.v
  v8api/window.v
Labels: documentation, enhancement, script

#115 Расположение temp, bls-ls-cfg + ошибки для выделенного кода.
  addins/bsl_analyze.epf
  addins/bsl_analyze.js
  addins/src/bsl_analyze/bsl_analyze.xml
  addins/src/bsl_analyze/bsl_analyze/Ext/ObjectModule.bsl
  addins/src/bsl_analyze/bsl_analyze/Forms/Настройка.xml
  addins/src/bsl_analyze/bsl_analyze/Forms/Настройка/Ext/Form.bin
  addins/src/bsl_analyze/bsl_analyze/Forms/Форма.xml
  addins/src/bsl_analyze/bsl_analyze/Forms/Форма/Ext/Form.bin
Labels: script

#136 Фиксы для 8.3.15.* #131
  v8api/file.v
  v8api/metadata.v
Labels: core, Запуск конфигуратора

#135 удалить символы #13 перед проверкой кода
  addins/bsl_analyze.js
Labels: script

#138 Fixes for 8.3.16.xxxx
  v8api/bkendui.v
  v8api/metadata.v
Labels: core, Запуск конфигуратора

#139 Missed 8.3.17.1823 support
  v8api/bkendui.v
Labels: core, Запуск конфигуратора

#143 Исправление вылетов Снегопата на отладке и некоторых модальных вызовах - для 8.3.17 и выше
  v8api/bkendui.v
Labels: core, Запуск конфигуратора

#145 8.3.17.1989
  v8api/bkendui.v
  v8api/metadata.v
Labels: core, Запуск конфигуратора

#153 Улучшены шаблоны кода при выборе из подсказки + Подстановка правильных шаблонов Попытка-Исключение
  engine/StockListInterceptor.as
  engine/keywords.as
Labels: core, подсказка Снегопата

#149 Выравнивание по последней запятой
  addins/format.js
Labels: enhancement, script
